version: '3.8'
services:
  client:
    build:
      context: ./client
    container_name: client
    ports:
      - "4200:4200"
    depends_on:
      - api
      - webapi
  
  api:
    build:
      context: ./nodeapi
    container_name: api
    restart: always
    ports:  
      - "5000:5000"
    depends_on:
      - nginx
      - emongo

  webapi:
    build:
      context: ./javaapi
    restart: always
    container_name: webapi
    ports: 
      - "9000:9000"
    depends_on:
      - emartdb

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    restart: always

    
  emongo:
    image:  mongo:4
    container_name: emongo
    ports:
      - "27017:27017"
    environment: 
      - MONGO_INITDB_DATABASE=epoc

  emartdb:
    image: mysql:8.0.33
    container_name: emartdb
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=emartdbpass
      - MYSQL_DATABASE=books